regions:
  - us-east-1
  - eu-west-1
  - global

# 2. Safety Blocklist (Must contain at least one ID, even if dummy)
blocklist:
  - "999999999999"

# 3. Targeted Account Configuration
accounts:
  "311810547417": # 12-digit AWS Account ID
    filters:
      IAMUser:
        - "terraform-ecs-deployer"
      IAMUserAccessKey:
        - type: "glob"
          value: "terraform-ecs-deployer -> *"
      IAMUserPolicyAttachment:
        - type: "glob"
          value: "terraform-ecs-deployer -> *"
